### PR TITLE
Add hint about creation vs updating events

### PR DESCRIPTION
**Pull request by marcusstenbeck**
Not sure whether my language is correct or if this is actually how it works, but I thought I might as well add a PR.

### CODE REVIEW

**Comment by goloroden** [comment]
@marcusstenbeck Thanks a lot for your PR 😊 

It looks great, thank you very much!
To be able to merge it – could you please sign the CLA?

**Comment by marcusstenbeck** [comment]
@goloroden Signed :)

**Comment by goloroden** [comment]
I'm very sorry that I have to ask you for another thing again (I didn't see that at first): Could you please make your change to the `latest` docs instead of the `1.2.0` docs?

**Comment by goloroden** [comment]
Closed in favour of #26

**Pull request closed without merging**
