### PR TITLE
Added the authentication article.

### PR DESCRIPTION
**Pull request by co16353sidak**
As discussed in issue (Fixes thenativeweb/wolkenkit#80)
I have added the initial draft for the authentication article.
Please review and suggest changes 🥇 

Will add into the metadata later, once the article is Final and  Approved

@goloroden

### CODE REVIEW

**Comment by goloroden** [comment]
Hi @co16353sidak 😊 

First of all, thanks a lot for coming up with a PR that fast!
Before we go into the details of wording, I thought it may be a good idea to give you some feedback on the general outline.

I basically like what you did, but I think that there are three aspects that need further processing:

1. I am not sure if everyone who is going to read this is familiar with token-based authentication. So it may be a good idea to explain what an identity provider is, what a relying party is, what a token is, and so on… This does not need to go into too much detail, but I think it would be a good idea to prepare the stage. In the Auth0 article this was not needed, since I assumed that everyone who is going to read the Auth0 blog is already familiar with those concepts.
2. We should point out that using Auth0 is just an example, and you could use any other identity provider that uses OpenID Connect as well. We should avoid that people think that Auth0 has to be used. While they provide a great service, you can also use several other solutions here as well, either hosted or on-premise, such as ADFS, Keycloak, …
3. In the Auth0 article there is a section `Thinking about security`, which explains how the security concepts work in wolkenkit, that you need to authenticate, and that you then also need to authorize commands, events, and queries. This is missing IMHO, but this is pretty essential for understanding what you are doing.

What do you think of this?

**Comment by co16353sidak** [comment]
@goloroden Ah, good pointers, I will get on this and make the changes for a second draft.
1. should I be adding these explanations inside the main paragraphs or as a glossary type system in the end.
2. 👍 
3. 👍

**Comment by goloroden** [comment]
Regarding your question I‘d suggest to do this in a paragraph in the introduction.

**Comment by co16353sidak** [comment]
Implemented all the suggestions, please review this second draft @goloroden

**Comment by goloroden** [comment]
@co16353sidak Thanks for providing the updates, I will review this soon!

One last thing - could you please add yourself as a contributor to the package.json file?

**Comment by co16353sidak** [comment]
> One last thing - could you please add yourself as a contributor to the `package.json` file?

Am I supposed to follow any alphabetical order on this ?

**Comment by goloroden** [comment]
Thanks for asking :-)

The list is sorted historically, so just add yourself to the end of the list.

**Comment by co16353sidak** [comment]
Added @goloroden, I hope everything should be ready now for your review.

**Comment by co16353sidak** [comment]
Hey @goloroden any updates on this, would love to finish this and move on to other ways to contribute to this repo

**Comment by goloroden** [comment]
I'm at a conference this week, giving a number of workshops, so this is why I have not yet fully reviewed your PR (although I wanted to). Tomorrow, I'll be on the train for several hours, so then I finally should have the time to do it 👍

**Comment by goloroden** [comment]
@co16353sidak I now had some time to take a closer look at the guide you have written so far. Although I like the basic idea, I have seen that you copied over the code samples and text snippets from the Auth0 blog post without adjusting them to match the current wolkenkit version. E.g., the `when` section does not exist any more, and you're still targeting the `1.2.0` runtime (which is pretty old now).

Could you please update the guide to match the latest version, and ensure for all code samples that they actually work? In addition, suppose someone has not yet followed the previous guide, it would be great to provide a download with the initial setup.

And: In the [issue](https://github.com/thenativeweb/wolkenkit/issues/80), there was a [checklist](https://stackoverflow.com/questions/48266381/wolkenkit-redirects-to-auth0-even-when-user-is-logged-in/48266737#48266737) mentioned that should also be taken into consideration. AFAICS you have not yet integrated that one into the text. Could you please review this as well, and come up with an idea of how to involve those steps in the text?

**Comment by co16353sidak** [comment]
thank you for the good feedback, I will make the required changes by tomorrow @goloroden

**Comment by goloroden** [comment]
@co16353sidak It just wanted to write to you as well today… we have decided to rewrite the authentication / authorization part of wolkenkit, and hence a lot of the implementation details have changed, as well as the API for the user.

Hence before you continue working on this, it would make sense to wait until the new API is available. I'm really sorry that I have not told you about that before, but the decision is pretty new. So, I don't want to discourage you, but please wait a while, until we have finished the transition to the new API.

Sorry for these news 😢

**Comment by goloroden** [comment]
PS: Since the guide needs a rewrite from scratch then, I'd close this PR for now. I hope you don't mind.

**Comment by co16353sidak** [comment]
@goloroden Oh, I was away from GitHub for a few days and I didn't have time to check the main repo for the transitions. 
Yes it makes sense to close the PR, let's wait for the new API to roll out and then I can send another PR with more valid content

**Pull request closed without merging**
